[versions]
kotlin = '2.2.20'
shadow = '9.1.0'

apollo-api = '1.2.6'
apollo-wrapper = '0.0.1'

spigot = '1.8.8-R0.1-SNAPSHOT'

adventure-api = '4.26.1'
adventure-platform-bukkit = '4.4.1'

menu-api = '1.5.5'

packetevents-api = '2.11.1'

lombok = '1.18.46'

entity-lib = '668b0d0a68'

actionbar-api = '0.0.9'

jackson = "2.18.3"

fastutil = "8.5.19"

[plugins]
shadow = { id = 'com.gradleup.shadow', version.ref = 'shadow' }

[libraries]
kotlin-gradle-plugin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin' }

apollo-api = { module = 'com.lunarclient:apollo-api', version.ref = 'apollo-api' }
apollo-wrapper = { module = 'io.github.kuraiwtf:apollo-wrapper', version.ref = 'apollo-wrapper' }

spigot = { module = 'org.spigotmc:spigot', version.ref = 'spigot' }

adventure-bom = { module = 'net.kyori:adventure-bom', version.ref = 'adventure-api' }
adventure-platform-bukkit = { module = 'net.kyori:adventure-platform-bukkit', version.ref = 'adventure-platform-bukkit' }
adventure-mini-message = { module = 'net.kyori:adventure-text-minimessage' }

packetevents-spigot = { module = 'com.github.retrooper:packetevents-spigot', version.ref = 'packetevents-api' }

lombok = { module = 'org.projectlombok:lombok', version.ref = 'lombok' }

entity-lib = { module = 'com.github.SuperCrafting:EntityLib', version.ref = 'entity-lib' }

actionbar-api = { module = 'com.github.kuraiwtf:actionbar-api', version.ref = 'actionbar-api' }

jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }

[bundles]
apollo = ['apollo-api', 'apollo-wrapper']
adventure = ['adventure-platform-bukkit', 'adventure-mini-message']
jackson = ['jackson-core', 'jackson-databind', 'jackson-annotations', 'jackson-datatype-jdk8', 'jackson-datatype-jsr310']
